services:
  database:
    image: mysql:8.0
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - database.env
    volumes:
      - sql:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  backend:
    image: ds-backend
    container_name: backend
    networks:
      - backend
    ports:
      - 8448:8448
    env_file:
      - database.env 
      - backend.env
    depends_on:
      database:
        condition: service_healthy
        restart: true

volumes:
  sql:

networks:
  backend: